[project]
name = "code-typing-derby"
version = "0.1.0"
description = "Mastering programming languages syntax and idioms"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115",
    "ruff>=0.6.9",
]

[tool.uv]
dev-dependencies = [
    "fastapi-cli>=0.0.5",
]
